theme: jekyll-theme-slate
title: Скрипты для Power BI и Excel
description: Альтернативные интерфейсы подключения по API (коннекторы) к источникам данных с документированным кодом на языке M для Power Query
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"
avatar: "/img/avatar-icon.png"

author:
  name: Илья Назаров

social-network-links:
  rss: true
  facebook: iliah.nazarov
  github: meta110
  telegram: IlyaNazarov
  youtube: channel/UC0gJoc8up4o9wdOlkUr9CAg

gtag: "UA-162274913-1"
gtm: "GTM-TVX6GTJ"
