theme: jekyll-theme-cayman
title: Скрипты для Power BI и Excel
description: Альтернативные интерфейсы подключения по API (коннекторы) к источникам данных с документированным кодом на языке M для Power Query
